version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: codgen_zookeeper
    ports:
      - ${ZOOKEEPER_PORT}:${ZOOKEEPER_PORT}
  kafka:
    image: wurstmeister/kafka:2.11-1.1.0
    container_name: kafka-nodejs-example-kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: sales-topic:1:1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_PORT}
    ports:
      - ${KAFKA_PORT}:${KAFKA_PORT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  producer:
    build: ./services/producer
    container_name: codgen_producer
    command: sh -c "dockerize -wait tcp://zookeeper:${ZOOKEEPER_PORT} -wait tcp://kafka:${ZOOKEEPER_PORT} npm start"
    depends_on:
      - zookeeper
      - kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_PORT}
    ports:
      - ${PRODUCER_PORT}:${PRODUCER_PORT}
  consumer:
    build: ./services/consumer
    container_name: codgen_consumer
    command: sh -c "dockerize -wait tcp://zookeeper:${ZOOKEEPER_PORT} -wait tcp://kafka:${ZOOKEEPER_PORT} npm start"
    depends_on:
      - zookeeper
      - kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_PORT}