swagger: "2.0"
info:
  version: "0.0.1"
  title: Codgen App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /codgen:
    # binds a127 app logic to a route
    x-swagger-router-controller: codgen
    post:
      operationId: startGeneration
      consumes:
        - application/json
      parameters:
       - in: body
         name: generated
         description: The json to generate.
         schema:
            $ref: '#/definitions/ShemaFromFractal'  
      responses:
        200:
          description: Successfully generated
          
          # responses may fall through to errors
        default:
          description: Error
  /swagger:
    x-swagger-pipe: swagger_raw
definitions:
  ShemaFromFractal:           # <----------
    type: object
    required:
      - elements
    properties:
      elements:
        type: array
        items: 
          $ref: "#/definitions/ShemaItem"
      id:
        type: string
  ShemaItem:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: integer
      name:
        type: string
      links:
        type: array
        items: 
          type: object
      params:
        type: object
      methods:
        type: object
      